-- +migrate Up notransaction
CREATE TABLE IF NOT EXISTS students (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    identity_number VARCHAR(255) NOT NULL ,
    name VARCHAR(256) ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;

-- +migrate Down
DROP TABLE IF EXISTS students;